### ISSUE TITLE
Song subtitles are set to "Off" by default

### ISSUE THREAD

**Issue by darklinkpower** [CommitteeOfZero/chn-patch#2]
**Bug description**
Song subtitles are set to "Off" by default. In case it matters, it was with the GOG patch

**To reproduce**
1. Install patch
2. Open launcher. `Song subtitles` option will be set to `Off` by default

**Screenshots**
![image](https://user-images.githubusercontent.com/1389286/216749049-49b94d99-033e-4494-ad87-fdcbbc79ab86.png)

**Comment by theAeon** [comment]
Ditto Steam.
